export const seedSchemes = [
  {
    name: "PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)",
    name_hi: "पीएम-किसान (प्रधानमंत्री किसान सम्मान निधि)",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    ministry_hi: "कृषि एवं किसान कल्याण मंत्रालय",
    category: "agriculture",
    description:
      "Income support of ₹6,000 per year in three equal installments to all land-holding farmer families. Funds are directly transferred to bank accounts of beneficiaries.",
    description_hi:
      "सभी भूमिधारक किसान परिवारों को तीन समान किस्तों में ₹6,000 प्रति वर्ष की आय सहायता। लाभार्थियों के बैंक खातों में सीधे धनराशि हस्तांतरित की जाती है।",
    eligibility_criteria: JSON.stringify([
      "Must be a land-holding farmer family",
      "Valid Aadhaar card linked to bank account",
      "Land records must be updated in state/UT database",
    ]),
    required_documents: JSON.stringify([
      "Aadhaar Card",
      "Bank account passbook",
      "Land ownership documents",
      "Domicile certificate",
    ]),
    application_process: JSON.stringify([
      "Visit the PM-KISAN portal or nearest Common Service Centre (CSC)",
      "Register with Aadhaar number and bank details",
      "Submit land ownership documents",
      "Verification by state nodal officer",
      "Once approved, installments credited automatically",
    ]),
    benefit_amount: "₹6,000 per year (₹2,000 × 3 installments)",
    benefit_type: "Direct Benefit Transfer (DBT)",
    deadline: null,
    official_link: "https://pmkisan.gov.in",
    tags: "farmer,agriculture,income support,DBT,kisan",
    is_new: 0,
    min_age: 18,
    max_age: null,
    max_income: null,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)",
    name_hi: "आयुष्मान भारत - प्रधानमंत्री जन आरोग्य योजना (पीएम-जय)",
    ministry: "Ministry of Health & Family Welfare",
    ministry_hi: "स्वास्थ्य एवं परिवार कल्याण मंत्रालय",
    category: "healthcare",
    description:
      "World's largest health insurance scheme providing ₹5 lakh per family per year for secondary and tertiary hospitalization. Covers 1,950+ medical packages including surgeries, diagnostics, and medicines.",
    description_hi:
      "विश्व की सबसे बड़ी स्वास्थ्य बीमा योजना जो माध्यमिक और तृतीयक अस्पताल में भर्ती के लिए प्रति परिवार प्रति वर्ष ₹5 लाख प्रदान करती है। 1,950+ चिकित्सा पैकेज शामिल हैं।",
    eligibility_criteria: JSON.stringify([
      "Family must be listed in SECC 2011 database",
      "Annual household income below ₹2.5 lakh",
      "No age limit for beneficiaries",
    ]),
    required_documents: JSON.stringify([
      "Aadhaar Card",
      "Ration Card",
      "SECC inclusion proof",
      "Family ID / reference number",
    ]),
    application_process: JSON.stringify([
      "Check eligibility on mera.pmjay.gov.in using mobile number or ration card",
      "Visit nearest Ayushman Bharat empanelled hospital",
      "Show Aadhaar card and verify identity at Ayushman Mitra desk",
      "Get e-card generated at the hospital",
      "Avail cashless treatment at any empanelled hospital",
    ]),
    benefit_amount: "₹5,00,000 per family per year",
    benefit_type: "Health Insurance (Cashless)",
    deadline: null,
    official_link: "https://pmjay.gov.in",
    tags: "health,insurance,hospital,cashless,PMJAY,ayushman",
    is_new: 0,
    min_age: null,
    max_age: null,
    max_income: 250000,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
    name_hi: "प्रधानमंत्री आवास योजना - ग्रामीण (पीएमएवाई-जी)",
    ministry: "Ministry of Rural Development",
    ministry_hi: "ग्रामीण विकास मंत्रालय",
    category: "housing",
    description:
      "Provides financial assistance for construction of pucca houses with basic amenities to eligible rural households. ₹1.20 lakh in plains and ₹1.30 lakh in hilly/difficult areas.",
    description_hi:
      "पात्र ग्रामीण परिवारों को बुनियादी सुविधाओं के साथ पक्के मकान के निर्माण के लिए वित्तीय सहायता। मैदानी क्षेत्रों में ₹1.20 लाख और पहाड़ी/कठिन क्षेत्रों में ₹1.30 लाख।",
    eligibility_criteria: JSON.stringify([
      "Houseless or living in kutcha/dilapidated house",
      "Household must be in SECC 2011 data",
      "Must not own a pucca house anywhere in India",
      "Priority to SC/ST, freed bonded labourers, minorities",
    ]),
    required_documents: JSON.stringify([
      "Aadhaar Card",
      "Bank account details",
      "SECC data inclusion proof",
      "Job card (MGNREGA) if available",
      "Photograph of existing dwelling",
    ]),
    application_process: JSON.stringify([
      "Gram Sabha identifies eligible beneficiaries from SECC data",
      "Verification by block/district authorities",
      "Beneficiary selects house design from approved options",
      "First installment released after sanction",
      "Subsequent installments on completion milestones (geo-tagged photos)",
    ]),
    benefit_amount: "₹1,20,000 (plains) / ₹1,30,000 (hilly areas)",
    benefit_type: "Construction Grant",
    deadline: "2025-03-31",
    official_link: "https://pmayg.nic.in",
    tags: "housing,rural,pucca house,construction,PMAY",
    is_new: 0,
    min_age: 18,
    max_age: null,
    max_income: 300000,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
    name_hi: "महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (मनरेगा)",
    ministry: "Ministry of Rural Development",
    ministry_hi: "ग्रामीण विकास मंत्रालय",
    category: "employment",
    description:
      "Guarantees 100 days of wage employment per year to every rural household whose adult members volunteer to do unskilled manual work. Wages range from ₹220-₹330/day depending on the state.",
    description_hi:
      "प्रत्येक ग्रामीण परिवार को जिसके वयस्क सदस्य अकुशल शारीरिक कार्य करने के इच्छुक हैं, प्रति वर्ष 100 दिनों के वेतन रोजगार की गारंटी। राज्य अनुसार ₹220-₹330/दिन मजदूरी।",
    eligibility_criteria: JSON.stringify([
      "Must be a rural household member",
      "Age 18 years or above",
      "Willing to do unskilled manual work",
      "Must have a Job Card",
    ]),
    required_documents: JSON.stringify([
      "Aadhaar Card",
      "Job Card (issued by Gram Panchayat)",
      "Bank/Post Office account details",
      "Photograph",
    ]),
    application_process: JSON.stringify([
      "Apply for Job Card at Gram Panchayat",
      "Job card issued within 15 days with photo",
      "Submit written application for work at Gram Panchayat",
      "Work must be provided within 15 days of application",
      "If no work provided, entitled to unemployment allowance",
    ]),
    benefit_amount: "₹220–₹330 per day (state-dependent)",
    benefit_type: "Wage Employment",
    deadline: null,
    official_link: "https://nrega.nic.in",
    tags: "employment,rural,wage,NREGA,manual work,job guarantee",
    is_new: 0,
    min_age: 18,
    max_age: null,
    max_income: null,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "Sukanya Samriddhi Yojana",
    name_hi: "सुकन्या समृद्धि योजना",
    ministry: "Ministry of Finance",
    ministry_hi: "वित्त मंत्रालय",
    category: "women_child",
    description:
      "Small savings scheme for the girl child offering high interest rate (8.2% p.a.). Deposits can be made until the girl turns 15, and the account matures when she turns 21. Tax benefits under Section 80C.",
    description_hi:
      "बालिकाओं के लिए उच्च ब्याज दर (8.2% प्रतिवर्ष) वाली लघु बचत योजना। बालिका के 15 वर्ष होने तक जमा और 21 वर्ष पर खाता परिपक्व। धारा 80C के तहत कर लाभ।",
    eligibility_criteria: JSON.stringify([
      "Girl child must be below 10 years of age at account opening",
      "Only one account per girl child",
      "Maximum two accounts per family (exceptions for twins/triplets)",
      "Parent/guardian must be Indian resident",
    ]),
    required_documents: JSON.stringify([
      "Birth certificate of girl child",
      "Identity proof of parent/guardian (Aadhaar/PAN)",
      "Address proof",
      "Passport-size photographs",
    ]),
    application_process: JSON.stringify([
      "Visit nearest post office or authorized bank",
      "Fill the account opening form",
      "Submit required documents with minimum deposit of ₹250",
      "Account activated and passbook issued",
      "Make deposits annually (min ₹250, max ₹1.5 lakh/year)",
    ]),
    benefit_amount: "8.2% interest p.a. (tax-free maturity)",
    benefit_type: "Savings Scheme",
    deadline: null,
    official_link: "https://www.nsiindia.gov.in",
    tags: "girl child,savings,interest,tax benefit,women,SSY",
    is_new: 0,
    min_age: null,
    max_age: null,
    max_income: null,
    gender_restriction: "female",
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "PM Mudra Yojana (PMMY)",
    name_hi: "पीएम मुद्रा योजना (पीएमएमवाई)",
    ministry: "Ministry of Finance",
    ministry_hi: "वित्त मंत्रालय",
    category: "startup_msme",
    description:
      "Provides loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises. Three categories: Shishu (up to ₹50,000), Kishore (₹50,001–₹5 lakh), Tarun (₹5,00,001–₹10 lakh). No collateral required.",
    description_hi:
      "गैर-कॉर्पोरेट, गैर-कृषि लघु/सूक्ष्म उद्यमों को ₹10 लाख तक का ऋण। तीन श्रेणियां: शिशु (₹50,000 तक), किशोर (₹50,001-₹5 लाख), तरुण (₹5,00,001-₹10 लाख)।",
    eligibility_criteria: JSON.stringify([
      "Indian citizen with a business plan for non-farm income-generating activity",
      "Small business owners, shopkeepers, vendors, artisans",
      "No collateral or guarantor needed",
      "Existing businesses or new startups eligible",
    ]),
    required_documents: JSON.stringify([
      "Identity proof (Aadhaar/PAN/Voter ID)",
      "Address proof",
      "Business plan or proposal",
      "Passport-size photographs",
      "Caste certificate (if applicable for subsidies)",
    ]),
    application_process: JSON.stringify([
      "Visit any bank, NBFC, or MFI offering Mudra loans",
      "Select appropriate category (Shishu/Kishore/Tarun)",
      "Submit application with business plan and documents",
      "Bank evaluates and sanctions the loan",
      "Mudra card issued for working capital needs",
    ]),
    benefit_amount: "Up to ₹10,00,000 (loan)",
    benefit_type: "Collateral-free Loan",
    deadline: null,
    official_link: "https://www.mudra.org.in",
    tags: "loan,business,startup,MSME,entrepreneur,mudra,collateral-free",
    is_new: 0,
    min_age: 18,
    max_age: null,
    max_income: null,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "Atal Pension Yojana (APY)",
    name_hi: "अटल पेंशन योजना (एपीवाई)",
    ministry: "Ministry of Finance (PFRDA)",
    ministry_hi: "वित्त मंत्रालय (पीएफआरडीए)",
    category: "financial_inclusion",
    description:
      "Guaranteed pension scheme for unorganized sector workers. Monthly pension of ₹1,000 to ₹5,000 after age 60, based on contribution. Government co-contributes 50% for eligible subscribers.",
    description_hi:
      "असंगठित क्षेत्र के श्रमिकों के लिए गारंटीकृत पेंशन योजना। योगदान के आधार पर 60 वर्ष की आयु के बाद ₹1,000 से ₹5,000 मासिक पेंशन।",
    eligibility_criteria: JSON.stringify([
      "Age between 18-40 years",
      "Must have a savings bank/post office account",
      "Not a member of any statutory social security scheme",
      "Must have valid mobile number linked to bank",
    ]),
    required_documents: JSON.stringify([
      "Bank/Post Office savings account",
      "Aadhaar Card",
      "Mobile number",
      "Nominee details",
    ]),
    application_process: JSON.stringify([
      "Visit bank where you have savings account",
      "Fill up the APY registration form",
      "Choose pension amount (₹1,000–₹5,000/month)",
      "Auto-debit set up from savings account",
      "Pension starts at age 60",
    ]),
    benefit_amount: "₹1,000–₹5,000 per month (post age 60)",
    benefit_type: "Pension",
    deadline: null,
    official_link: "https://www.npscra.nsdl.co.in/scheme-details.php",
    tags: "pension,retirement,unorganized sector,APY,savings",
    is_new: 0,
    min_age: 18,
    max_age: 40,
    max_income: null,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "PM Ujjwala Yojana 2.0",
    name_hi: "पीएम उज्ज्वला योजना 2.0",
    ministry: "Ministry of Petroleum & Natural Gas",
    ministry_hi: "पेट्रोलियम एवं प्राकृतिक गैस मंत्रालय",
    category: "energy",
    description:
      "Provides free LPG connections to women from BPL households. Ujjwala 2.0 extends to migrant families and requires only self-declaration. Includes free first refill and stove.",
    description_hi:
      "बीपीएल परिवारों की महिलाओं को मुफ्त एलपीजी कनेक्शन प्रदान करती है। उज्ज्वला 2.0 प्रवासी परिवारों तक विस्तारित। पहली मुफ्त रिफिल और चूल्हा शामिल।",
    eligibility_criteria: JSON.stringify([
      "Woman of 18 years or above from BPL household",
      "No existing LPG connection in the household",
      "For Ujjwala 2.0: migrant families with self-declaration of address",
      "Name in SECC-2011 list or belongs to SC/ST/most backward/tea garden/forest dweller category",
    ]),
    required_documents: JSON.stringify([
      "Aadhaar Card (self & family members)",
      "BPL ration card / SECC list proof",
      "Passport-size photograph",
      "Bank account details",
      "For migrants: self-declaration of address",
    ]),
    application_process: JSON.stringify([
      "Visit nearest LPG distributor",
      "Fill up KYC form and submit documents",
      "Verification by distributor",
      "Free connection with stove and first refill issued",
      "Subsequent refills at subsidized rate via DBT",
    ]),
    benefit_amount: "Free LPG connection + first refill + stove",
    benefit_type: "In-kind (LPG Connection)",
    deadline: null,
    official_link: "https://www.pmuy.gov.in",
    tags: "LPG,gas,cooking,women,BPL,energy,ujjwala",
    is_new: 1,
    min_age: 18,
    max_age: null,
    max_income: 200000,
    gender_restriction: "female",
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "National Scholarship Portal - Post Matric Scholarship for SC Students",
    name_hi: "राष्ट्रीय छात्रवृत्ति पोर्टल - अनुसूचित जाति छात्रों हेतु पोस्ट मैट्रिक छात्रवृत्ति",
    ministry: "Ministry of Social Justice & Empowerment",
    ministry_hi: "सामाजिक न्याय एवं अधिकारिता मंत्रालय",
    category: "education",
    description:
      "Scholarship for SC students studying at post-matriculation level (Class 11 and above). Covers tuition fees, maintenance allowance, and study materials. Available across all recognized institutions.",
    description_hi:
      "पोस्ट मैट्रिक स्तर (कक्षा 11 और ऊपर) में पढ़ने वाले अनुसूचित जाति के छात्रों के लिए छात्रवृत्ति। ट्यूशन फीस, रखरखाव भत्ता और अध्ययन सामग्री शामिल।",
    eligibility_criteria: JSON.stringify([
      "Student must belong to Scheduled Caste",
      "Family annual income not exceeding ₹2.5 lakh",
      "Studying in post-matriculation course (Class 11+)",
      "Enrolled in recognized institution",
    ]),
    required_documents: JSON.stringify([
      "Caste certificate",
      "Income certificate",
      "Previous year marksheet",
      "Aadhaar Card",
      "Bank passbook (student's own account)",
      "Admission letter / bonafide certificate",
    ]),
    application_process: JSON.stringify([
      "Register on National Scholarship Portal (scholarships.gov.in)",
      "Fill fresh/renewal application form",
      "Upload required documents",
      "Submit and note application ID",
      "Institute verifies → District verifies → State approves",
      "Scholarship amount credited to student's bank account",
    ]),
    benefit_amount: "Tuition fees + ₹550–₹1,200/month maintenance",
    benefit_type: "Scholarship",
    deadline: "2025-12-31",
    official_link: "https://scholarships.gov.in",
    tags: "scholarship,education,SC,post matric,students,tuition",
    is_new: 0,
    min_age: 15,
    max_age: 35,
    max_income: 250000,
    gender_restriction: null,
    category_restriction: "sc",
    disability_required: 0,
  },
  {
    name: "Startup India Seed Fund Scheme",
    name_hi: "स्टार्टअप इंडिया सीड फंड योजना",
    ministry: "Department for Promotion of Industry and Internal Trade (DPIIT)",
    ministry_hi: "उद्योग और आंतरिक व्यापार संवर्धन विभाग (डीपीआईआईटी)",
    category: "startup_msme",
    description:
      "Provides financial assistance to startups for proof of concept, prototype development, product trials, market entry, and commercialization. Grants up to ₹20 lakh and investments up to ₹50 lakh.",
    description_hi:
      "स्टार्टअप को अवधारणा प्रमाण, प्रोटोटाइप विकास, उत्पाद परीक्षण, बाजार प्रवेश और व्यावसायीकरण के लिए वित्तीय सहायता। ₹20 लाख तक अनुदान और ₹50 लाख तक निवेश।",
    eligibility_criteria: JSON.stringify([
      "DPIIT-recognized startup",
      "Incorporated not more than 2 years ago",
      "Must have a business idea for a product/service with market fit",
      "Should not have received more than ₹10 lakh monetary support from government",
    ]),
    required_documents: JSON.stringify([
      "DPIIT recognition certificate",
      "Certificate of incorporation",
      "Business plan / pitch deck",
      "PAN of the startup",
      "Bank account details of the startup",
    ]),
    application_process: JSON.stringify([
      "Register on Startup India portal (startupindia.gov.in)",
      "Apply through selected incubator on the portal",
      "Incubator evaluates the application",
      "If selected, grant/investment disbursed in milestones",
      "Regular progress reports to incubator",
    ]),
    benefit_amount: "Up to ₹50,00,000 (grant + investment)",
    benefit_type: "Grant / Equity Investment",
    deadline: "2026-03-31",
    official_link: "https://seedfund.startupindia.gov.in",
    tags: "startup,seed fund,entrepreneur,innovation,DPIIT,grant",
    is_new: 1,
    min_age: 18,
    max_age: null,
    max_income: null,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "PM Fasal Bima Yojana (PMFBY)",
    name_hi: "पीएम फसल बीमा योजना (पीएमएफबीवाई)",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    ministry_hi: "कृषि एवं किसान कल्याण मंत्रालय",
    category: "agriculture",
    description:
      "Crop insurance scheme protecting farmers against crop loss due to natural calamities, pests, and diseases. Premium: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops. Rest paid by government.",
    description_hi:
      "प्राकृतिक आपदाओं, कीटों और बीमारियों से फसल हानि के खिलाफ किसानों की सुरक्षा करने वाली फसल बीमा योजना। प्रीमियम: खरीफ 2%, रबी 1.5%, वाणिज्यिक फसल 5%।",
    eligibility_criteria: JSON.stringify([
      "All farmers including sharecroppers and tenant farmers",
      "Must have crop sown on notified land",
      "Voluntary for non-loanee farmers; bundled for loanee farmers",
    ]),
    required_documents: JSON.stringify([
      "Aadhaar Card",
      "Bank account details",
      "Land records / lease agreement",
      "Sowing certificate from revenue authority",
    ]),
    application_process: JSON.stringify([
      "Visit nearest bank, CSC, or PMFBY portal",
      "Fill crop insurance application before cutoff date",
      "Pay farmer share of premium",
      "In case of crop loss, report to insurance company within 72 hours",
      "Assessment by insurance company; claim settled to bank account",
    ]),
    benefit_amount: "Full sum insured (crop-value based)",
    benefit_type: "Crop Insurance",
    deadline: "2025-07-31",
    official_link: "https://pmfby.gov.in",
    tags: "crop,insurance,agriculture,farmer,natural disaster,PMFBY",
    is_new: 0,
    min_age: 18,
    max_age: null,
    max_income: null,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "Beti Bachao Beti Padhao",
    name_hi: "बेटी बचाओ बेटी पढ़ाओ",
    ministry: "Ministry of Women & Child Development",
    ministry_hi: "महिला एवं बाल विकास मंत्रालय",
    category: "women_child",
    description:
      "National campaign to address declining child sex ratio and empower the girl child through education. Includes awareness programs, enforcement of PC-PNDT Act, and convergent actions across ministries.",
    description_hi:
      "घटते बाल लिंगानुपात को संबोधित करने और शिक्षा के माध्यम से बालिकाओं को सशक्त बनाने का राष्ट्रीय अभियान।",
    eligibility_criteria: JSON.stringify([
      "Families with girl children",
      "No specific income or age criteria — awareness campaign",
      "District-level programs open to all residents",
    ]),
    required_documents: JSON.stringify([
      "No specific documents for awareness programs",
      "For linked schemes: Aadhaar, birth certificate of girl child",
    ]),
    application_process: JSON.stringify([
      "Contact district Women & Child Development office",
      "Participate in awareness programs and events",
      "Enroll girls in school and linked schemes (SSY, scholarships)",
      "Report violations of PC-PNDT Act if encountered",
    ]),
    benefit_amount: "Awareness campaign (linked to SSY, scholarships)",
    benefit_type: "Awareness + Linked Benefits",
    deadline: null,
    official_link: "https://wcd.nic.in/bbbp-schemes",
    tags: "girl child,education,women,awareness,gender equality,BBBP",
    is_new: 0,
    min_age: null,
    max_age: null,
    max_income: null,
    gender_restriction: "female",
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
    name_hi: "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना (आईजीएनओएपीएस)",
    ministry: "Ministry of Rural Development",
    ministry_hi: "ग्रामीण विकास मंत्रालय",
    category: "senior_citizens",
    description:
      "Monthly pension of ₹200 (60-79 years) or ₹500 (80+ years) to BPL elderly citizens. States often add top-up amounts. Part of National Social Assistance Programme (NSAP).",
    description_hi:
      "बीपीएल वृद्ध नागरिकों को ₹200 (60-79 वर्ष) या ₹500 (80+ वर्ष) मासिक पेंशन। राज्य अक्सर अतिरिक्त राशि जोड़ते हैं। राष्ट्रीय सामाजिक सहायता कार्यक्रम (NSAP) का हिस्सा।",
    eligibility_criteria: JSON.stringify([
      "Age 60 years or above",
      "Must belong to BPL household",
      "Name in BPL list of the state/UT",
    ]),
    required_documents: JSON.stringify([
      "Age proof (Aadhaar / birth certificate / voter ID)",
      "BPL card / certificate",
      "Bank/post office account details",
      "Passport-size photograph",
    ]),
    application_process: JSON.stringify([
      "Apply at Gram Panchayat (rural) or ULB office (urban)",
      "Submit application form with documents",
      "Verification by local authority",
      "Sanctioned by District/Sub-District office",
      "Pension credited monthly to bank/post office account",
    ]),
    benefit_amount: "₹200/month (60-79 yrs) or ₹500/month (80+ yrs)",
    benefit_type: "Monthly Pension",
    deadline: null,
    official_link: "https://nsap.nic.in",
    tags: "pension,old age,senior citizen,BPL,NSAP,elderly",
    is_new: 0,
    min_age: 60,
    max_age: null,
    max_income: 200000,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 0,
  },
  {
    name: "Sugamya Bharat Abhiyan (Accessible India Campaign)",
    name_hi: "सुगम्य भारत अभियान (एक्सेसिबल इंडिया कैम्पेन)",
    ministry: "Department of Empowerment of Persons with Disabilities (DEPwD)",
    ministry_hi: "दिव्यांगजन सशक्तिकरण विभाग (डीईपीडब्ल्यूडी)",
    category: "disability",
    description:
      "Nationwide campaign to make public spaces, transport, and ICT accessible for persons with disabilities. Includes assistive device distribution, accessibility audits, and sign language interpreter training.",
    description_hi:
      "दिव्यांगजनों के लिए सार्वजनिक स्थलों, परिवहन और आईसीटी को सुगम बनाने का राष्ट्रव्यापी अभियान। सहायक उपकरण वितरण, सुगम्यता लेखापरीक्षा और सांकेतिक भाषा दुभाषिया प्रशिक्षण शामिल।",
    eligibility_criteria: JSON.stringify([
      "Persons with disabilities (40%+ disability certificate)",
      "Indian citizen",
      "For assistive devices: income below ₹15,000/month",
    ]),
    required_documents: JSON.stringify([
      "Disability certificate (40%+ from certified authority)",
      "Aadhaar Card",
      "Income certificate",
      "Passport-size photograph",
    ]),
    application_process: JSON.stringify([
      "Contact District Disability Rehabilitation Centre (DDRC)",
      "Register for assistive device camps",
      "Submit application with disability and income certificates",
      "Assessment by medical team at camp",
      "Devices distributed at camp or delivered later",
    ]),
    benefit_amount: "Free assistive devices + accessible infrastructure",
    benefit_type: "In-kind (Devices & Infrastructure)",
    deadline: null,
    official_link: "https://accessibleindia.gov.in",
    tags: "disability,accessible,assistive devices,PwD,inclusion,barrier-free",
    is_new: 0,
    min_age: null,
    max_age: null,
    max_income: 180000,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 1,
  },
  {
    name: "PM Vishwakarma Yojana",
    name_hi: "पीएम विश्वकर्मा योजना",
    ministry: "Ministry of Micro, Small & Medium Enterprises",
    ministry_hi: "सूक्ष्म, लघु एवं मध्यम उद्यम मंत्रालय",
    category: "startup_msme",
    description:
      "End-to-end support for traditional artisans and craftspeople through recognition, skill training, toolkit incentive, credit support (up to ₹3 lakh), and market linkage. Covers 18 traditional trades.",
    description_hi:
      "पारंपरिक कारीगरों और शिल्पकारों को मान्यता, कौशल प्रशिक्षण, टूलकिट प्रोत्साहन, ऋण सहायता (₹3 लाख तक) और बाजार संपर्क के माध्यम से समग्र सहायता। 18 पारंपरिक व्यापार शामिल।",
    eligibility_criteria: JSON.stringify([
      "Traditional artisan or craftsperson working with hands and tools",
      "Engaged in one of 18 notified trades (carpenter, blacksmith, goldsmith, potter, etc.)",
      "Age 18 years or above",
      "Must not be in government service or organized sector",
    ]),
    required_documents: JSON.stringify([
      "Aadhaar Card",
      "Ration card / family ID",
      "Bank account details",
      "Mobile number",
      "Skill/trade photograph",
    ]),
    application_process: JSON.stringify([
      "Register on PM Vishwakarma portal via CSC or mobile app",
      "Gram Panchayat / ULB verifies artisan identity",
      "Receive PM Vishwakarma certificate and ID card",
      "Enroll in 5-day basic training (₹500/day stipend)",
      "Receive toolkit incentive (up to ₹15,000)",
      "Apply for collateral-free credit (₹1 lakh first tranche, ₹2 lakh second)",
    ]),
    benefit_amount: "Up to ₹3,00,000 (credit) + ₹15,000 (toolkit) + training",
    benefit_type: "Credit + Training + Toolkit",
    deadline: "2028-03-31",
    official_link: "https://pmvishwakarma.gov.in",
    tags: "artisan,craftsman,traditional,toolkit,training,MSME,vishwakarma",
    is_new: 1,
    min_age: 18,
    max_age: null,
    max_income: null,
    gender_restriction: null,
    category_restriction: null,
    disability_required: 0,
  },
];
